-define(DEFAULT_TEST_COUNT, 1000).
-define(DEFAULT_SAMPLE_SIZE, 10).
-define(DEFAULT_LIST_SIZE, 100).
-define(DEFAULT_MAX_INT, 1000).
-define(DEFAULT_MAX_TRIES, 100).
-define(COLLECT_SRV, rapperl_collect_server).
